### ISSUE TITLE
Possible PD bug

### ISSUE THREAD

**Issue by DevilDexter22** [Mikihero/BetterCoinflips#10]
When using a coin in the Pocket Dimension, the player stops getting damage and can stay infinitly in the PD

EDIT: Found the Issue. Sry my bad. Ignore this!

**Comment by Mikihero** [comment]
Out of curiosity, what was causing the issue? Also I'll have to test something but I think _there is_ a way this could cause such behaviour albeit it'd be very rare

**Comment by DevilDexter22** [comment]
Actually i've had an old version installed of your plugin as this bug wasnt discovered before today. As i updsted to your latest release (3d ago) the bug was fixed. Maybe some exiled error cause of 13.0 Update. But actually i really dont know the exact thing that was causing the issue.

Greets
________________________________

**Comment by Mikihero** [comment]
Tbh I've no clue what was causing the bug for you before you updated but now I'm concerned that if someone rolls the right effect it could after running out cancel the PD damage. Not sure if that's what would happen so I'll test it +- tomorrow.

**Comment by Mikihero** [comment]
Shouldn't be possible
