### ISSUE TITLE
The Coin gives only good things from 13.0 update

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#13]
`Is tails:` is always `false`
Image of the console with `debug: true`:
![image](https://github.com/Mikihero/BetterCoinflips/assets/76474182/b20511da-6bd2-434e-98f2-58d4f789daba)

Video of using the coin:
https://github.com/Mikihero/BetterCoinflips/assets/76474182/cde5209c-0cc2-441a-9f97-2b9ffd604bcf

**Comment by Czekoloczek** [comment]
oh i was so lazy with reporting that bug that someone was a little bit faster then me xD

**Comment by Mikihero** [comment]
dw your report was much more detailed, it's most likely an exiled issue with the event I'm using, I'll get on it within the next few days once I come back from vacation

**Comment by Czekoloczek** [comment]
don't worry, take your time
I hope you have a nice holiday :D

**Comment by Czekoloczek** [comment]
yep it's fixed
[Exiled.Events] ev.IsTails should no longer always be false in the FlippingCoin event. [https://github.com/Exiled-Team/EXILED/pull/1918]

**Comment by Czekoloczek** [comment]
probably i didn't test it yet xD

**Comment by Czekoloczek** [comment]
ye it's working
thx for the help :D
