### ISSUE TITLE
if you get turned into another class in pd you don't get damaged

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#15]
Version: 3.0.2

Description: If you get teleported to the PD through the Pocket Corroding effect and then get turned into another class (from `class_swap_effect_chance` or `zombie_fc_effect_chance`) you don't get any damage.

Steps to reproduce:
- Get a coin
- Get `PocketCorroding` effect from the coin (so you get teleported to PD)
- Get your class swapped or turn into 049-2 by the coin

What is supposed to happen: You still should get damaged from the pd
What actually happens: You don't get damaged from the pd
  
  
Attachments: 
https://github.com/Mikihero/BetterCoinflips/assets/76474182/dc541d1c-5d69-4a7a-8318-fe0e4000afb1

**Comment by Mikihero** [comment]
fixed in 3.0.3
