### ISSUE TITLE
Translations bronk

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#16]
Version: 3.0.3

Description: Every translation doesn't work except for the new one (`coin_no_uses_message:`) and if the coin breaks (after some uses) the plugin uses the `coin_no_uses_message:` instead of the `coin_breaks_message:`

Steps to reproduce:

- Get a coin
- Throw a coin
- No translation D:
- Get the coin to break
- The wrong translation is displayed D: 

What is supposed to happen: The translations should work normally
What actually happens: The translations aren't working

Attachments:

https://github.com/Mikihero/BetterCoinflips/assets/76474182/a02619d4-e720-45ce-a758-9b19f19a3943

**Comment by Mikihero** [comment]
I'm on the case, not yet sure what's causing this (other than me not thinking straight). Good news: my test are consistently as bugged as yours were. Bad news: I don't yet know why but that's only a matter of time.

**Comment by Mikihero** [comment]
3.0.4 fixes all the issues (at least on my end lel)
