### ISSUE TITLE
Effect Pocket Corroding not working very well

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#17]
If you add the `PocketCorroding` effect to the `bad_effects:` and you get teleported by it, you only get damaged for 5 seconds (7 damage) and then you can sit in the Pocket Dimension endlessly.

Please either make it so if you add the Pocket Corroding effect it doesn't end until you exit the Pocket Dimension (I think the game removes the effect by itself if you exit the Dimension, but I'm not sure)
or
Add the chance to teleport to it in the Bad effects (where is hp_reduction_effect, tp_to_class_d_cells, etc.)

https://github.com/Mikihero/BetterCoinflips/assets/76474182/22b16f23-e138-4e7c-a093-fc8e4e47aa3e

**Comment by Mikihero** [comment]
Good to know, once I come back from vacation I'll need to take a look at everything 106 related since his rework changed some things to which I don't think I adapted.

**Comment by Mikihero** [comment]
fixed in 3.1.1
