### ISSUE TITLE
Suggestion: Able to change percentages effects

### ISSUE THREAD

**Issue by Remi321** [Mikihero/BetterCoinflips#2]
Hello. We now have this plugin in use but the nuke turns on like 4 times every round because of the high chance you’ll get that specific effect. Maybe it would a very nice idea to give admins the “power” to adjust the percentages of each event happening.

it’s the same for lights out inside of the facility. It happens a little to much my players have stated.

**Comment by Mikihero** [comment]
That's something I will keep in mind and try to adress with the next release, an easy way to do so would be to add more effects but as I am not creative it's hard for me to just think of a bunch just like that, any suggestions on some new effects would be great!

**Comment by Remi321** [comment]
Hello @Mikihero ,

I saw you had edited the config.cs file to add specific chances. How do i get that? I updated the plugin but it's not a version change.

**Comment by Mikihero** [comment]
> I saw you had edited the config.cs file to add specific chances. How do i get that? I updated the plugin but it's not a version change.
The changes I made are part of the next update that will contain these config options and a few other small things. I pushed these changes to github because it's easier for me to keep track of my work this way, but the update itself is not out yet. I am planning on having it finished +- this weekend.

**Comment by Mikihero** [comment]
> Thank you so much for the information, I'll be waiting on the update! keep up the great work!

The update is now out! I will close this issue as it has been dealt with but if you find any bugs, please open another one.
