### ISSUE TITLE
Player Swap Improvment

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#22]
Make it so tutorials won't get swaped so staff will not get swaped when for example in jail
(so this doesn't happen again xD)
https://cdn.discordapp.com/attachments/878308123528536114/1160608923460587521/SCP_Secret_Laboratory_2023.10.08_-_18.02.14.02.DVR_-_Trim.mp4?ex=6535484a&is=6522d34a&hm=1acd20111af4fa5663d1bb216a33fda45553ccfa469b8860687b05ea569ecc23&

**Comment by Mikihero** [comment]
Should be fixed in 4.2.1
