### ISSUE TITLE
Plugin Version 4.5.0 always uses the default translation and config

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#31]
The plugin isn't using the translation file and instead is using the default broadcasts

also, the config was restored to the default settings for some reason

**Comment by Czekoloczek** [comment]
after I've changed the config and restarted the server the plugin still uses the default values

**Comment by Mikihero** [comment]
right, I completely forgot to mention that I removed the prefix used in configs and translations (if there is not prefix the name will be used instead, so before your config and translations started with better_cf: and then the rest, and now it's better_coinfglips:), you need to change the section name from better_cf: to better_coinflips: (if you're not sure how it should look like just generate a new config by restarting your server with no config and compare the new one with your old one)
