### ISSUE TITLE
Random room teleport can teleport you out of the map

### ISSUE THREAD

**Issue by Czekoloczek** [Mikihero/BetterCoinflips#34]
The coin can teleport you behind the rocks in the entrance zone
![image](https://github.com/Mikihero/BetterCoinflips/assets/76474182/2cb7a0ee-10de-4634-80a2-e78a37cf477e)

(I didn't test this, I got this information from a player)

**Comment by Mikihero** [comment]
remove `EzCollapsedTunnel` from `RoomsToTeleport` in your config, I'll remove it from the default config, tho the release won't be coming until at least march 13th
