### ISSUE TITLE
Can you add Chinese, please?

### ISSUE THREAD

**Issue by ShengGT** [Mikihero/BetterCoinflips#37]
using System.Collections.Generic;
using System.ComponentModel;
using Exiled.API.Interfaces;

namespace BetterCoinflips.Configs
{
    public class Translations : ITranslation
    {
        // 如果硬币破裂，则会将其添加到效果消息中。 
        [Description("如果硬币破裂，则会将其添加到效果消息中。")]
        public string CoinBreaksMessage { get; set; } = "\n此外，您的硬币使用过多，它坏了。";

        // 当一枚硬币被注册但没有使用时，广播的消息是  
        [Description("当一枚硬币被注册但没有使用时，广播的消息是")]
        public string CoinNoUsesMessage { get; set; } = "你的硬币一开始就没有使用过！";

        public List<string> HintMessages { get; set; } = new()
        {
            "你的硬币落地时是反面朝上。",
            "你的硬币落地时是正面朝上。"
        };

        // 在这里，您可以为每种好的硬币效果设置消息。  
        [Description("为每种好的硬币效果设置消息。")]
        public string TossOnCooldownMessage { get; set; } = "你还不能投掷硬币。";
        public string RedCardMessage { get; set; } = "你获得了一张设施经理门禁卡！";
        public string ContainmentEngineerCardMessage { get; set; } = "你获得了一张收容工程师门禁卡！";
        public string MediKitMessage { get; set; } = "你收到了一个“医疗包”！";
        public string TpToEscapeMessage { get; set; } = "你现在可以逃跑了！这不就是你想要的吗？";
        public string MagicHealMessage { get; set; } = "你被神奇地治愈了！";
        public string HealthIncreaseMessage { get; set; } = "你的生命值增加了10%！";
        public string NeatHatMessage { get; set; } = "你得到了一顶整洁的帽子！";
        public string RandomGoodEffectMessage { get; set; } = "你得到了一个随机效果。";
        public string OneAmmoLogicerMessage { get; set; } = "你得到了一把枪。";
        public string LightbulbMessage { get; set; } = "你得到了一个闪亮的电灯泡！";
        public string PinkCandyMessage { get; set; } = "你得到了一颗漂亮的糖果！";
        public string BadRevoMessage { get; set; } = "这是什么怪物！？";
        public string EmptyHidMessage { get; set; } = "你刚刚得到了一个微型HID吗！？";
        public string ForceRespawnMessage { get; set; } = "有人重生了...可能吧。";
        public string SizeChangeMessage { get; set; } = "你被变成侏儒了。";
        public string RandomItemMessage { get; set; } = "你得到了一个随机物品！";

        // 在这里，您可以为每种坏的硬币效果设置消息。  
        [Description("为每种坏的硬币效果设置消息。")]
        public string HpReductionMessage { get; set; } = "你的生命值减少了30%。";
        public string TpToClassDCellsMessage { get; set; } = "你被传送到了D级人员牢房。";
        public string TpToClassDCellsAfterWarheadMessage { get; set; } = "你被传送到了放射性区域。";
        public string RandomBadEffectMessage { get; set; } = "你得到了一个随机效果。";
        public string WarheadStopMessage { get; set; } = "核弹头已被停止。";
        public string WarheadStartMessage { get; set; } = "核弹头已被启动。";
        public string LightsOutMessage { get; set; } = "熄灯了。";
        public string LiveGrenadeMessage { get; set; } = "小心你的头！";
        public string TrollFlashMessage { get; set; } = "你听到什么了吗？";
        public string TpToRandomScpMessage { get; set; } = "你被传送到了一个SCP身边。";
        public string SmallDamageMessage { get; set; } = "你失去了15点生命值。";
        public string HugeDamageMessage { get; set; } = "你失去了大量生命值";
        public string PrimedVaseMessage { get; set; } = "你奶奶来看你了！";
        public string ShitPantsMessage { get; set; } = "你刚刚把裤子弄脏了。";
        public string FakeScpKillMessage { get; set; } = "你刚刚杀了一个SCP吗";
        public string TurnIntoScpMessage { get; set; } = "变为SCP风格的LOL!";
        public string InventoryResetMessage { get; set; } = "你丢失了你的物品。";
        public string ClassSwapMessage { get; set; } = "这就是我所说的UNO反转卡!";
        public string InstantExplosionMessage { get; set; } = "你被炸飞了。";
        public string PlayerSwapMessage { get; set; } = "你的物品栏与一名随机玩家的物品栏互换了。";
        public string PlayerSwapIfOneAliveMessage { get; set; } = "你本应与其他人交换位置，但其他人都不在了!";
        public string KickMessage { get; set; } = "再见!";
        public string SpectSwapPlayerMessage { get; set; } = "你刚刚让某人的游戏轮次变得更好了!";
        public string SpectSwapSpectMessage { get; set; } = "你被选为一名随机观众来替换这名玩家!";
        public string SpectSwapNoSpectsMessage { get; set; } = "你真幸运，因为没有观众可以替换你的位置。";
        public string TeslaTpMessage { get; set; } = "你是个电力迷吗?";
        public string TeslaTpAfterWarheadMessage { get; set; } = "你被传送到了放射性区域。";

        [Description("这个消息将对两名玩家同时广播。")]
        public string InventorySwapMessage { get; set; } = "你的物品栏与一名随机玩家的物品栏互换了。";
        public string InventorySwapOnePlayerMessage { get; set; } = "你不能与任何人交换，因此你正在失去生命值。";
        public string RandomTeleportMessage { get; set; } = "你被随机传送了。";
        public string RandomTeleportWarheadDetonatedMessage { get; set; } = "核弹头爆炸了，所以你只得到了一颗糖果。";
        public string HandcuffMessage { get; set; } = "你被逮捕了，因为呃...犯下了战争罪行...或是其他什么。";
    }
}

**Comment by Mikihero** [comment]
all translations are done by the user, the translation file is in english by default, but it generates on each server after installation allowing each user to translate it however they please
