### ISSUE TITLE
Last time's mistake

### ISSUE THREAD

**Issue by SHTLUOLEI** [Mikihero/BetterCoinflips#6]
I updated beta21 today, and then I updated it, and found that the last error would still be in

![Screenshot 2023-01-13 143059](https://user-images.githubusercontent.com/112939682/212253104-a39eed2a-ba55-41d0-963c-932e06bfea49.png)

**Comment by Mikihero** [comment]
Did you update exiled on your server?

**Comment by SHTLUOLEI** [comment]
Yes, the server and plug-in are both beta21

**Comment by Mikihero** [comment]
I'll take a look at it later, it's possible that it wasn't actually fixed in beta21

**Comment by SHTLUOLEI** [comment]
Instead of fixing previous bugs, beta21 has a bunch of bugs

**Comment by Mikihero** [comment]
It fixed old ones, it created new ones. That's the essence of programming.

**Comment by Mikihero** [comment]
@SHTLUOLEI check if this issue still persists on the latest release
