### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by LaFesta1749** [Mikihero/BetterCoinflips#9]
Will there be an update to exiled 7 and SCP:SL 13.0 ?

**Comment by Mikihero** [comment]
> Will there be an update to exiled 7 and SCP:SL 13.0 ?
If one is required yes, not sure when exactly but a week should probably be enough.

**Comment by LaFesta1749** [comment]
Thank you. As of now it's dropping errors when used.

**Comment by sergio24m** [comment]
Right now it crashes and doesn't work in exiled 7, they're right
Hopefully a new update drops soon

**Comment by Mikihero** [comment]
Any errors? There is basically no way in which this plugin could cause a crash so I'd like to see a more detailed explanation of what happens with any errors included.

**Comment by Mikihero** [comment]
@sergio24m I forgot to mention but the plugin has been updated, see if it works for you now.
